# Generated by Django 3.0.7 on 2021-02-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.IntegerField(blank=True, choices=[(0, 'Сразу'), (1, 'Электронно'), (2, 'Наличностью')], null=True, verbose_name='оплата'),
        ),
    ]
